version: "3.7"
services:
  backend:
    build: backend
    secrets:
      - db-password
    environment:
      - DB_HOST=YOUR_CLOUD_SQL_PUBLIC_IP
      - DB_PORT=5432
      - DB_USER=YOUR_DB_USER
      - DB_NAME=example
    depends_on:
      - proxy
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend
secrets:
  db-password:
    file: db/password.txt
