name: Deploy to Cloud Run

env:
  PROJECT_ID: commit-hr-manuel-data
  BACKEND_IMAGE_URL: northamerica-south1-docker.pkg.dev/commit-hr-manuel-data/docker/backend-tf2
  PROXY_IMAGE_URL: northamerica-south1-docker.pkg.dev/commit-hr-manuel-data/docker/proxy-tf2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker northamerica-south1-docker.pkg.dev

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ env.BACKEND_IMAGE_URL }}:latest -f backend/Dockerfile .
          docker push ${{ env.BACKEND_IMAGE_URL }}:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy backend-tf \
            --image ${{ env.BACKEND_IMAGE_URL }}:latest \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated

  dockerize-and-deploy-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker northamerica-south1-docker.pkg.dev

      - name: Build and Push Proxy Docker Image
        run: |
          docker build -t ${{ env.PROXY_IMAGE_URL }}:latest -f proxy/Dockerfile .
          docker push ${{ env.PROXY_IMAGE_URL }}:latest

      - name: Deploy Proxy to Cloud Run
        run: |
          gcloud run deploy proxy-tf \
            --image ${{ env.PROXY_IMAGE_URL }}:latest \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated